# TODO Someting skaffold didn't restart node. ex: auth
apiVersion: skaffold/v2alpha3
kind: config
deploy:
  kubectl:
    manifests:
    - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
  - image: frasnym/auth
    context: auth
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: 'src/**/*.ts'
        dest: .
  - image: frasnym/client
    context: client
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: '**/*.js'
        dest: .
  - image: frasnym/tickets
    context: tickets
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: 'src/**/*.ts'
        dest: .
  - image: frasnym/orders
    context: orders
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: 'src/**/*.ts'
        dest: .
  - image: frasnym/expiration
    context: expiration
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: 'src/**/*.ts'
        dest: .