apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration  # Tell deployment what pod to use
  template:
    metadata:
      labels:
        app: expiration  # Label of the pod
    spec:
      containers:
      - name: expiration
        image: frasnym/expiration
        env:
        - name: NATS_CLIENT_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NATS_URL
          value: 'http://nats-srv:4222'
        - name: NATS_CLUSTER_ID
          value: ticketing
        - name: REDIS_HOST
          value: expiration-redis-srv
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        # ports:
        # - containerPort: <Port>

