apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders  # Tell deployment what pod to use
  template:
    metadata:
      labels:
        app: orders  # Label of the pod
    spec:
      containers:
      - name: orders
        image: frasnym/orders
        env:
        - name: NATS_CLIENT_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NATS_URL
          value: 'http://nats-srv:4222'
        - name: NATS_CLUSTER_ID
          value: ticketing
        - name: MONGO_URI
          value: 'mongodb://orders-mongo-srv:27017/orders'
        - name: JWT_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: JWT_KEY
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        # ports:
        # - containerPort: <Port>
---
apiVersion: v1
kind: Service
metadata:
  name: orders-srv
spec:
  selector:
    app: orders # Tell which pod to given access to
  ports:
  - name: orders
    protocol: TCP
    port: 3000
    targetPort: 3000

